# Generated by Django 5.0.7 on 2024-07-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0017_task_cluster_alter'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='timeout_hook',
            field=models.CharField(blank=True, help_text='e.g. module.tasks.timeout_function', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='timeout_hook',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
